const mongoose = require('mongoose');

const EmployeeSchema = new mongoose.Schema({
  surname: { type: String, required: true },
  firstname: { type: String, required: true },
  middlename: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  position: { type: String, required: false },
  // Add PDS fields below
  nameExt: String,
  dateOfBirth: String,
  placeOfBirth: String,
  sex: String,
  civilStatus: String,
  height: String,
  weight: String,
  bloodType: String,
  gsis: String,
  pagibig: String,
  philhealth: String,
  sss: String,
  tin: String,
  agencyEmployeeNo: String,
  citizenship: String,
  dualType: String,
  citizenshipCountry: String,
  spouse_surname: String,
  spouse_first: String,
  spouse_middle: String,
  spouse_extension: String,
  spouse_occupation: String,
  spouse_employer: String,
  spouse_businessAddress: String,
  spouse_tel: String,
  children: [{ name: String, dob: String }],
  father_surname: String,
  father_first: String,
  father_middle: String,
  father_ext: String,
  mother_surname: String,
  mother_first: String,
  mother_middle: String,
  pdsStatus: { type: String, default: "Pending" }
});

module.exports = mongoose.model('Employee', EmployeeSchema);